engines:
  rubocop:
    enabled: true
    #checks:
    #  Rubocop/Metrics/ClassLength:
    #    enabled: false
  brakeman:
    enabled: false
  eslint:
    enabled: true
  csslint:
    enabled: false
  duplication:
    enabled: true
    config:
      languages:
      - javascript:
ratings:
  paths:
  - "**.js"
exclude_paths:
- spec/**/*
- node_modules/**/*
- "**/vendor/**/*"

