before_install:
   - echo -n | openssl s_client -connect scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-

before_script:
  - npm install -g istanbul
  - npm install -g mocha
  - npm install -g gulp

script: 'make test-cov'
after_success: 'make coveralls'

sudo: false
language: node_js
node_js:
  - "6"
  - "5"
  - "4"

global:
  env:
    - CXX=g++-4.8
    - secure: "Zs8vVAgzr2GDMCpZuu6ELM8GCI3uW6ZS/fMZ+V42SWOA3AIlSEacpr/zlxYt7QNX1doeYL73CUXM93/ttRfBya/dMyBGvSocY1gfSmT+rYgxI8wyZEa75w5r6uZWFP8xVmlta6sIGIXxXHAw4jp0D9gh4dmxGdsOrv0DoK6F/7+md8XuEA5wBbCiRd8hvwPVrpzqj0NlKr3lvykBaHGA6+JY/qjW0bdrrFfdsXc6yJOZXAoMGieHp+V2d/1pSGx4WdhA1oPDwD32VZ+ZL04TlJJ6Yem6KPQNgKApQm4W4wNHRjSCQcsODV4/tFHP9e/CK0pwwjJ5FKwk4BS5wiI+xRKvbtpA9cl7tGehf90q4pV1uP3H1US1Rgmsm7WC/2Gq8z7W7ZYlLpiB8fVT54WN9re5pqp47BiaOYXyUpXHsnXIp53ASRO+poM7svP+DHVvP13wLDXI9g5YUyvDKI85H1Ww1l1fGB/lZBlBTyBp+pVDn5HVhEstwtPGJwbyTNvO08tC6n26LQyDkpXO0HNTsvNlSvSaB2H98ETFORiesu/DG6nVu43zcwRXK2kwXLQ3iChRPUzN2MhTUXqXhKoEPzHHmm/XYA5JrNuyH5+2ueK3oWfscbiGl7TL2hb4wkoYpdXrdtqK78JCv6/+INlOWLrg3HHqo5lML9AWFo9upPQ="

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
  coverity_scan:
    project:
      name: "m4l1c3/gulp-bundle-files"
      description: "Build submitted via Travis CI"
    notification_email: jon@jonsomnia.com
      build_command_prepend: ""
      build_command:   ""
      branch_pattern: master