before_install:
   - echo -n | openssl s_client -connect scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-

before_script:
  - npm install -g istanbul
  - npm install -g mocha
  - npm install -g gulp

script: 'make test-cov'
after_success: 'make coveralls'

sudo: false
language: node_js
node_js:
  - "8"
  - "6"
  - "5"
  - "4"

env:
  global:
    - secure: "VSLXvPUK7zu6JAH/P+4YNcrDDeHGZEkWwGcLn5ASWRKLdZm1InTjK7efBbKVXPVAn1+myWJaM4X2/P1Po+h/LSqHJNKsUOujZRuJLLzFhwwKruusmnxJcsDccA7VrdLmnbCbNdpYjhycH34H5dUUPZu8eaYEyKyvGmtGpxQMBOWOGopZvqBgmpV0WRxqg4DO0MBWjwUhPhMz/006bTUYDAcvNzuxZ+W4f3KiLHMsBRD+6fcWlUb8aZSkzSnZClCNGNknenkOVteHvERtvNSKhSpBspjpsZ944IU2ZYnEAzu4ubs0MGhHYpgbZJX36B8ZK6iKyxwY4GtTkJp+5321+lolEGzL30oimx5yEVYDkPcw/nssMRYsdwBK5XRRJ7WriT1fAxHxoNNPpvO+LOI3vYtwv3ItnnyfLFZupvDB2wGNoMdwnxIRVAHYNPDxHHgMCgwjaUdhRpz+b+pggQX8s/LMG738eEs7amXDcqxZ7kkt4BefVgwjaqkl8l2a484WVCFlOVEHTJgVhqFgbYQ2iQa3m07dN92lrztuyt7zrfaUcyKcP9lV1IyrbNQbdooRt8udsClHo/Eo5I9ybCN/gSKxeWy9y6e9cJL+g/rBy+XJcbfp+JjvJNXVJsonVfXCUCICLDL2nwWKhh3CYnJJDB3TwmlJsg3Ul0mXxlptwrI="

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
  coverity_scan:
    project:
      name: "m4l1c3/gulp-bundle-files"
      description: "Build submitted via Travis CI"
    notification_email: jon@jonsomnia.com
    build_command_prepend: ""
    build_command:   ""
    branch_pattern: master
