before_script: 'npm install -g istanbul && npm install -g mocha'
script: 'make test-cov'
after_success: 'make coveralls'

sudo: false
language: node_js
node_js:
  - "5"
  - "4"
#  - "0.12"
#  - "0.10"
